FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    nano \
    postgresql-client \
    mosquitto-clients \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*