services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: SIGMA-dev-container
    volumes:
      - ..:/sigma_project:cached
    ports:
      - "8500:8500"
    command: [ "sleep", "infinity" ]
    networks:
      - dev-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: SIGMA-postgres
    restart: always
    env_file:
      - ../backend/sigma-api/.env
    ports:
      - "5450:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-data: {}
